site_name: Christoph De Baene
site_url: https://christophdebaene.github.io
site_description: About life en technology
site_author: Christoph De Baene

repo_name: christophdebaene/christophdebaene.github.io
repo_url: https://github.com/christophdebaene/christophdebaene.github.io
edit_uri: ""

copyright: "Copyright &copy; 2004-2023 Christoph De Baene"

theme:
  language: en
  name: material  
  icon: 
    logo: material/book-open-page-variant  
  palette:
    - scheme: default
      toggle:
        icon: material/weather-night
        name: Switch to dark mode    
    - scheme: slate
      toggle:
        icon: material/weather-sunny
        name: Switch to light mode
  features:
    - navigation.indexes
    - navigation.footer    
    - navigation.instant
    - navigation.instant.progress
    - content.code.copy
    - content.code.select

plugins:
  - search
  - table-reader
  - tags:
      tags_file: blog/tags.md
  - blog:            
      post_url_format: "{slug}"
      post_excerpt: optional
      post_date_format: long
      post_url_date_format: yyyy/MM/dd
      archive: true      
      authors: false
  - rss:
      match_path: blog/posts/.* 
      date_from_meta:
        as_creation: date
      categories:
        - categories
        - tags 

markdown_extensions:
  - attr_list
  - admonition
  - md_in_html    
  - pymdownx.details
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.keys
  - pymdownx.tasklist
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.highlight:
      guess_lang: true
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
      extend_pygments_lang:
        - name: php
          lang: php
          options:
            startinline: true
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format

nav:
  - Blog: 
    - blog/index.md
    - blog/tags.md  

extra:
  social:
    - icon: material/twitter
      link: 'https://twitter.com/ChrisDeBaene'
    - icon: material/github
      link: 'https://github.com/christophdebaene'

  
extra_javascript:
    - assets/js/extra.js
extra_css:
    - assets/css/extra.css