site_name: Christoph De Baene
site_url: https://christophdebaene.be
site_description: About life en technology
site_author: Christoph De Baene

repo_name: christophdebaene/christophdebaene.github.io
repo_url: https://github.com/christophdebaene/christophdebaene.github.io
edit_uri: ""

copyright: "Copyright &copy; 2024 Christoph De Baene"

theme:
  language: en  
  name: material    
  custom_dir: overrides
  font:
    text: Roboto
    code: Roboto Mono
  icon: 
    logo: material/book-open-page-variant  
  palette:
    - scheme: default
      toggle:
        icon: material/weather-night
        name: Switch to dark mode
    - scheme: slate
      toggle:
        icon: material/weather-sunny
        name: Switch to light mode
  features:
    - navigation.indexes
    - navigation.footer    
    - navigation.instant
    - navigation.instant.progress
    - navigation.tabs
    - navigation.prune
    - navigation.sections    
    - content.code.copy
    - content.code.select

watch:
  - overrides/

plugins:
  - search  
  - table-reader
  - glightbox:
      effect: zoom
  - macros
  - tags:
      tags_file: blog/tags.md
  - blog:
      blog_toc: true
      post_url_format: "{slug}"
      post_excerpt: optional
      post_excerpt_separator: <!-- more -->
      post_date_format: long
      post_url_date_format: yyyy/MM/dd
      archive: true      
      authors: false
  - rss:
      match_path: blog/posts/.* 
      date_from_meta:
        as_creation: date
      categories:
        - categories
        - tags 
  - redirects:
      redirect_maps:
        'index.md': 'blog/index.md'

markdown_extensions:
  - attr_list
  - admonition
  - md_in_html    
  - pymdownx.details
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.keys
  - pymdownx.tasklist
  - pymdownx.superfences
  - pymdownx.inlinehilite
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.snippets
  - pymdownx.highlight:
      guess_lang: true
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
      extend_pygments_lang:
        - name: php
          lang: php
          options:
            startinline: true
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format

nav:  
  - Blog: 
    - blog/index.md
    - blog/tags.md  
  - Cheat Sheet:
    - cheat-sheet/windows/windows.md
    - cheat-sheet/javascript.md
    - cheat-sheet/python.md
    - cheat-sheet/typescript.md
  - disclaimer.md
  - Blog 2004-2014:
    - blog2004
  
extra:
  unit_price: 10
  analytics:
    provider: google
    property: G-ZVEYRCMQQP
      
  social:
    - icon: material/rss-box
      link: 'https://christophdebaene.github.io/feed_rss_created.xml'
    - icon: material/twitter
      link: 'https://twitter.com/ChrisDeBaene'
    - icon: material/github
      link: 'https://github.com/christophdebaene'

  
extra_javascript:
    - assets/js/favicons.config.js
    - assets/js/favicons.js
    
extra_css:
    - assets/css/favicons.css
    - assets/css/site.css